# Generated by Django 6.1.1 on 2026-09-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Rent', 'Rent'), ('Salary', 'Salary'), ('Electricity', 'Electricity'), ('Materials', 'Materials'), ('Maintenance', 'Maintenance'), ('Transport', 'Transport'), ('Marketing', 'Marketing'), ('Other', 'Other')], default='Other', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
