
"""
Django settings for boutique project.

Generated by 'django-admin startproject' using Django 6.1.1.
"""

from pathlib import Path
import os
import dj_database_url


# =========================================================
# BUILD PATHS
# =========================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# =========================================================
# SECURITY
# =========================================================

SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-l*o^+!tr7dqfx#z7ddi(ra$z4wj@t#43!%z7l9z+k)fqkxmkn5'
)

DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() == 'true'


ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
]

# Render automatically provides this environment variable
RENDER_EXTERNAL_HOSTNAME = os.environ.get(
    'RENDER_EXTERNAL_HOSTNAME'
)

if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# =========================================================
# APPLICATIONS
# =========================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'customers',
    'measurements',
    'orders',
    'payments',
    'inventory',
    'expenses',
    'dashboard',
    'userlogin',
    'products',
    'reporting',
]


# =========================================================
# MIDDLEWARE
# =========================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# =========================================================
# URL / WSGI
# =========================================================

ROOT_URLCONF = 'boutique.urls'

WSGI_APPLICATION = 'boutique.wsgi.application'


# =========================================================
# TEMPLATES
# =========================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',
                'django.contrib.auth.context_processors.auth',
            ],
        },
    },
]


# =========================================================
# DATABASE
# =========================================================
# Render:
#   DATABASE_URL -> PostgreSQL
#
# Local computer:
#   No DATABASE_URL -> SQLite fallback
# =========================================================

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# =========================================================
# PASSWORD VALIDATION
# =========================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =========================================================
# INTERNATIONALIZATION
# =========================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# =========================================================
# STATIC FILES
# =========================================================

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# =========================================================
# EMAIL / OTP - GMAIL SMTP
# =========================================================

GMAIL_USERNAME = os.environ.get(
    'SMART_BOUTIQUE_GMAIL',
    'amarnathcsesbm21@gmail.com'
)

GMAIL_APP_PASSWORD = os.environ.get(
    'SMART_BOUTIQUE_APP_PASSWORD',
    ''
)


MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
        'OPTIONS': {
            'host': 'smtp.gmail.com',
            'port': 587,
            'username': GMAIL_USERNAME,
            'password': GMAIL_APP_PASSWORD,
            'use_tls': True,
        },
    },
}


DEFAULT_FROM_EMAIL = GMAIL_USERNAME


# =========================================================
# DEFAULT PRIMARY KEY
# =========================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

